
export const ADD_TEACHER = 'ADD_TEACHER' 
export const GET_TEACHERS = 'GET_TEACHERS' 
export const SELECT_TEACHER = 'SELECT_TEACHER' 
export const EDIT_TEACHER = 'EDIT_TEACHER' 
export const REMOVE_TEACHER = 'REMOVE_TEACHER' 
